### ISSUE TITLE
07.02.2022 

### ISSUE THREAD

**Issue by isbendiyarovanezrin** [Parvana88/PragmatechFrontend#1]
Salam, Pərvanə.🙂

Repo 9 gündür güncəllənmir, hər gün güncəlləməyə çalışın.  Qovluq və fayl strukturuna çox fikir verin. CSS fayllarını və şəkilləri uyğun olaraq "css" və "img" adlı qovluğa əlavə etsəniz daha yaxşı olar. Yazdığınız kodları səliqəli yazmağa çalışın. 1-2 sətirdən artıq boşluq buraxmayın. "Index.html" yox "index.html" yazsanız daha yaxşı olar. Yəni ilk hərf kiçik hərflə başlasın. Demək olar ki, ancaq "px" ölçü vahidindən istifadə etmisiniz, "rem" (bunu daha çox məsləhət görürəm) və "em" kimi ölçü vahidlərindən də istifadə etməyə çalışın. Responsivlikdə çox köməyi olacaq.

Uğurlar!

**Comment by Parvana88** [comment]
Salam, Nazrin :)
Meslehetlere gore tesekkur edirem, dediyiniz formada hazirlamaga calisacam. Sadece olaraq heleki mende bezi melumatlar tam oturusmayib ona gore repo o formadadir. Calisacam sabah yeni repo yukleyim ,ne sehv gorseniz bildirin zehmet olmasa, onun uzerinde calisim.Tesekkurler onceden :)
